on: push

name: Make module index

jobs:
  render:
    name: Make index
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      # - name: Sync submodules
      #   run: |
      #     git submodule update --init --recursive
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: "4.2"
      - name: Generate the index
        run: Rscript create_index.R
      - name: Commit results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit modules.yml -m 'Generate index' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
